language: node_js
node_js:
- '6'
branches:
  all_branches: true
deploy:
  provider: heroku
  api_key:
    secure: PJuzePOm3xlxxwX3gkUzDBqtZudN+rQ7ybSK/y/AWWSO0lVz0PA12ndaYl2qjQIR8cQf2Ag5mEKl1b4dLpltbn9naDIK5+6sb06rDIu6FwpOtCrRBYUTLPOmcqBvMpXGpXRPk+E3T2dZBxNpu0beQM9D+teBjgdu245IpX1hoAxOPWpZFOqgkOJ9MslmPlcKkcjk03yzGiD1rDVGFyG7DYL3cxp9qlLzVI4851GiXJ2MWo6MBZVSeGbj+qpIIePfnYf4IL84HRZJRmqKKh0K+zdUnjvtVmc14GMR96L6jU18OnJiJl+ev2QjDeswtGhC+l1R27guSg2zpuKkHKO915JEN5SUhXR+RX3VpU8Qe//QkPpWX4m5ljZkVYXSNVdmm/IXGhU8rQAOg4UbCAgcENwZIMAa5ljP8LJDijOmu9nDuXJnhVm5nGjluQhWUNqi/1VBxeyFvgHfTGDLPOa1tMXZGrnQ44jvwJpsVR6t+chWgLP2c6FwKHA2kNLAv9C0MMRymGSA5cTPYKvsWlVJcexvNFTmSn+xl6Z3dFIaYOaI7DK//Y5KfkWl2HcG4qOtdiHfCwdytySwOiuyD8g+8yCjCwR30ESOViAwh5StNGJA+UvmTjhCCqH5DmWiMIjR4xCwm3OdNbqpIT8e/h2PJbgLtimqcE9jML+Izp3g1zg=
  app: square128
  on:
    repo: djkah11/2016_2_Rainbow_square